ALTER TABLE anchors
  ADD COLUMN IF NOT EXISTS domain VARCHAR(255),
  ADD COLUMN IF NOT EXISTS logo_url TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS fees JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS limits JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS compliance JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS supported_currencies TEXT[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS processing_time VARCHAR(255) NOT NULL DEFAULT 'Unknown',
  ADD COLUMN IF NOT EXISTS rating NUMERIC(3, 1),
  ADD COLUMN IF NOT EXISTS total_transactions INTEGER,
  ADD COLUMN IF NOT EXISTS verified BOOLEAN NOT NULL DEFAULT false;

UPDATE anchors
SET domain = COALESCE(domain, home_domain)
WHERE domain IS NULL AND home_domain IS NOT NULL;
