INSERT INTO anchors (
  id,
  name,
  public_key,
  webhook_secret,
  home_domain,
  domain,
  logo_url,
  description,
  status,
  fees,
  limits,
  compliance,
  supported_currencies,
  processing_time,
  rating,
  total_transactions,
  verified,
  enabled
) VALUES
(
  'anchor-1',
  'MoneyGram Access',
  'GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF',
  NULL,
  'moneygram.stellar.org',
  'moneygram.stellar.org',
  'https://example.com/moneygram-logo.png',
  'Global money transfer service with extensive agent network',
  'active',
  '{"deposit_fee_percent":1.5,"deposit_fee_fixed":0,"withdrawal_fee_percent":2.0,"withdrawal_fee_fixed":1.0,"min_fee":1.0,"max_fee":50.0}'::jsonb,
  '{"min_amount":10,"max_amount":10000,"daily_limit":25000,"monthly_limit":100000}'::jsonb,
  '{"kyc_required":true,"kyc_level":"intermediate","supported_countries":["US","CA","MX","GB","PH","IN"],"restricted_countries":["KP","IR","SY"],"documents_required":["government_id","proof_of_address"]}'::jsonb,
  ARRAY['USD','EUR','GBP','PHP','INR'],
  '1-3 business days',
  4.5,
  125000,
  true,
  true
),
(
  'anchor-2',
  'Circle USDC',
  'GBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX6',
  NULL,
  'circle.com',
  'circle.com',
  'https://example.com/circle-logo.png',
  'Leading USDC issuer with instant settlement',
  'active',
  '{"deposit_fee_percent":0.5,"deposit_fee_fixed":0,"withdrawal_fee_percent":0.5,"withdrawal_fee_fixed":0,"min_fee":0,"max_fee":25.0}'::jsonb,
  '{"min_amount":1,"max_amount":50000,"daily_limit":100000,"monthly_limit":500000}'::jsonb,
  '{"kyc_required":true,"kyc_level":"advanced","supported_countries":["US","CA","GB","EU"],"restricted_countries":["KP","IR","SY","CU"],"documents_required":["government_id","proof_of_address","ssn_or_tax_id"]}'::jsonb,
  ARRAY['USD','EUR'],
  'Instant',
  4.8,
  500000,
  true,
  true
),
(
  'anchor-3',
  'AnchorUSD',
  'GCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC3',
  NULL,
  'anchorusd.com',
  'anchorusd.com',
  'https://example.com/anchorusd-logo.png',
  'Fast and reliable USD anchor for Stellar network',
  'active',
  '{"deposit_fee_percent":1.0,"deposit_fee_fixed":0.5,"withdrawal_fee_percent":1.0,"withdrawal_fee_fixed":0.5,"min_fee":0.5,"max_fee":30.0}'::jsonb,
  '{"min_amount":5,"max_amount":25000,"daily_limit":50000}'::jsonb,
  '{"kyc_required":true,"kyc_level":"basic","supported_countries":["US","CA","MX","BR","AR"],"restricted_countries":["KP","IR"],"documents_required":["government_id"]}'::jsonb,
  ARRAY['USD'],
  '2-4 hours',
  4.2,
  75000,
  true,
  true
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  public_key = EXCLUDED.public_key,
  home_domain = EXCLUDED.home_domain,
  domain = EXCLUDED.domain,
  logo_url = EXCLUDED.logo_url,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  fees = EXCLUDED.fees,
  limits = EXCLUDED.limits,
  compliance = EXCLUDED.compliance,
  supported_currencies = EXCLUDED.supported_currencies,
  processing_time = EXCLUDED.processing_time,
  rating = EXCLUDED.rating,
  total_transactions = EXCLUDED.total_transactions,
  verified = EXCLUDED.verified,
  enabled = EXCLUDED.enabled,
  updated_at = NOW();
